#ifndef CONSTANTS_H
#define CONSTANTS_H

namespace frangiray {

#define MAX_RECURSION 5
#define DIRECT_LIGHTING_RAYS 2
#define INDIRECT_LIGHTING_RAYS 2
#define INDIRECT_LIGHTING_BOUNCES 2
#define OVERSCAN_STEP 6
#define LIGHT_ATTENUATION_SCALE 50

}

#endif // CONSTANTS_H
